variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "aws_region" {} 
variable "vpc_cidr" {} 
variable "vpc_name" {}
variable "IGW_name" {} 
variable "NAT_name" {}
variable "public_subnet_cidr" {}
variable "private_subnet_cidr" {}
variable "Instance_Name" {}
variable "public_subnet_name" {}
variable "private_subnet_name" {}
